"use client";

// Matches the widths generated by scripts/optimize-images.mjs.
const WIDTHS = [640, 750, 828, 1080, 1200, 1920];
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export default function localImageLoader({ src, width }: { src: string; width: number; quality?: number }) {
  // Remote/external images aren't pre-optimized — serve as-is.
  if (/^https?:\/\//.test(src)) return src;

  const targetWidth = WIDTHS.find((w) => w >= width) ?? WIDTHS[WIDTHS.length - 1];
  const lastDot = src.lastIndexOf(".");
  const withoutExtension = lastDot === -1 ? src : src.slice(0, lastDot);

  return `${BASE_PATH}${withoutExtension}@${targetWidth}.webp`;
}
